name: Publish Release

on:
  push:
    tags:
      - v*.*.*
      - "!v*.*.*-**"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    uses: ./.github/workflows/stage-lint.yml
  test:
    uses: ./.github/workflows/stage-test.yml
  publish:
    needs: [test, lint]
    uses: ./.github/workflows/stage-publish.yml
    with:
      goreleaser-args: -p 10 -f .goreleaser.yml --rm-dist --skip-validate --timeout 60m0s --release-notes=CHANGELOG_PENDING.md
  vscode:
    needs: [publish]
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win32
            arch: x64
          - os: windows-latest
            platform: win32
            arch: ia32
          - os: windows-latest
            platform: win32
            arch: arm64
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: arm64
          - os: ubuntu-latest
            platform: linux
            arch: armhf
          - os: ubuntu-latest
            platform: alpine
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: lsp-binaries
          if-no-files-found: error
      - name: build
        run: |
          mkdir bin
          gzip -d ${{steps.download.outputs.download-path}}/pulumi-lsp-${{matrix.platform}}-${{matrix.arch}}.gz bin
          make vscode-publish
      - name: publish
        run: |
          npm exec vsce -- publish --packagePath bin/*.vsix
