name: Test

on:
  workflow_call:
    inputs:
      commit-ref:
        description: Commit ref to check out and run tests against.
        default: ""
        required: false
        type: string
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PULUMI_TEST_PARALLEL: false

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.commit-ref }}
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          stable: ${{ matrix.go-stable }}
      - name: Test
        run: make test
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.18.x]
        go-stable: [true]
