name: Publish

on:
  workflow_call:
    inputs:
      goreleaser-args:
        required: true
        type: string
      vsce-full-release:
        required: false
        type: boolean
        default: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VSCE_PAT: ${{ secrets.VSCE_PAT }}

jobs:
  publish:
    name: Publish
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags || true
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: ${{ inputs.goreleaser-args }}
          version: latest
      - name: Upload assets as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lsp-binaries
          if-no-files-found: error
          path: goreleaser/pulumi-lsp_*
  vscode:
    name: Publish VS Code Extension
    needs: [publish]
    strategy:
      matrix:
        include:
          - platform: win32
            arch: x64
            file: windows_amd64_v1
          - platform: win32
            arch: arm64
            file: windows_arm64
          - platform: linux
            arch: x64
            file: linux_amd64_v1
          - platform: linux
            arch: arm64
            file: linux_arm64
          - platform: linux
            arch: armhf
            file: linux_arm64
          - platform: alpine
            arch: x64
            file: linux_arm64
          - platform: darwin
            arch: x64
            file: darwin_amd64_v1
          - platform: darwin
            arch: arm64
            file: darwin_arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.7.1
        with:
          repo: pulumi/pulumictl
          tag: v0.0.31
          cache: enable
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: lsp-binaries
      - name: npm install
        run: |
          cd editors/vscode && npm install
      - name: Prepare to Package
        run: |
          mkdir bin
          cp LICENSE editors/vscode/LICENSE
          cp README.md editors/vscode/README.md
          VERSION=$(git describe --tags --match 'v*.*.*')
          VERSION=${VERSION#v}
          jq ".version=\"${VERSION%-*}\"" editors/vscode/package.json > tmp.json
          mv tmp.json editors/vscode/package.json
          chmod u+x ${{steps.download.outputs.download-path}}/pulumi-lsp_${{matrix.file}}/*
          mv ${{steps.download.outputs.download-path}}/pulumi-lsp_${{matrix.file}}/* editors/vscode/
      - name: Package (Prereleas)
        if: ! inputs.vsce-full-release
        run: |
          cd editors/vscode
          npm exec vsce -- package --pre-release --target "${{ matrix.platform }}-${{ matrix.arch }}" --out ../../bin/
      - name: Publish (Pre-Release)
        if: ! inputs.vsce-full-release
        run: |
          npm exec vsce -- publish --pre-release --packagePath bin/*.vsix
      - name: Package (Release)
        if: inputs.vsce-full-release
        run: |
          cd editors/vscode
          npm exec vsce -- package --target "${{ matrix.platform }}-${{ matrix.arch }}" --out ../../bin/
      - name: Publish (Release)
        if: inputs.vsce-full-release
        run: |
          npm exec vsce -- publish --packagePath bin/*.vsix
